### ISSUE TITLE
No menu after updating configuration and uploading files

### ISSUE THREAD

**Issue by yeshpanovrustem** [DocTAG/doctag-core#3]
Hello. I've updated the configuration by uploading my own files and setting a new user name and a password. Now, I am able to log in, but the topic dropdown menu is empty, which is strange, for I uploaded the files following your json templates and wouldn't have been able to update the configuration if the files hadn't met the requirements, if I understand right. Please look into this at your earliest convenience.

![54eac7a6-1b70-4ed0-b1bb-16b7f7e4f360](https://user-images.githubusercontent.com/6375187/228214462-0aa70cf3-4329-4500-a53e-fc98ee432983.jpg)

**Comment by OrnellaIrrera** [comment]
Dear Rustem,
I'm sorry for the inconvenience. In order to understand what happend, and having more information about the status of the reuqest that retrieves the topics list, please, could you provide a screenshot of the window where you ran docker-compose up? Thank you.
Ornella

**Comment by yeshpanovrustem** [comment]
Hello. I am attaching a screenshot and a complete log file.
[dogtag.log](https://github.com/DocTAG/doctag-core/files/11107394/dogtag.log)
![screenshot](https://user-images.githubusercontent.com/6375187/228719534-585833ae-aa76-42f2-bdc3-a310445f697c.jpeg)

**Comment by OrnellaIrrera** [comment]
Dear Rustem,

Since the request seems to be correctly executed, can you provide the files you used to configure DocTag? You can send them on our thread of emails so that they are not publicly shared. If these files contain some information you do not want to share with us remove them before sharing. As soon as I receive the files I will test them so that I solve the issue.

Kind regards,
Ornella

**Comment by yeshpanovrustem** [comment]
Hello, Ornella. Thank you very much. I have been able to configure DocTAG with your help, but now I am experiencing another three issues.

ISSUE 1: In an exported annotated json file, I was expecting to see text spans under "mention_text", but it seems that DocTAG displays only Latin characters and digits. The characters that I am interested are not necessarily Latin, but also Cyrillic and Arabic ones (**EXPECTED**: "mention_text": "Футболдан әлем чемпионаты 2022 (كأس العالم لكرة القدم, FIFA World Cup 2022) — ФИФА-ның 22-ші футболдан әлем чемпионаты, финалдық кезеңі 2022 жылы Катарда өтті. Бұл 2002 жылдан бері Азияда, сондай-ақ Таяу Шығыста, Араб елінде және жалпы мұсылман әлемінде тұңғыш рет өткен алғашқы футбол біріншілігі. Сонымен қатар Катардағы чемпионат 32 құрама қатысқан соңғы турнир. Келесі 2026 жылғы әлем біріншілігінен бастап қатысушы құрамалар саны 48-ге дейін көбеймек. Бұл сайыстың тағы бір ерекшелігі — оның әдеттегідей жазда емес, қыста өткізілуі." , **OBSERVED**: ""mention_text": "   2022     FIFA World Cup 2022  - 22-      2022     2002    -                   32      2026        48-              "").

ISSUE 2: Say, in the string "байқауы.|дата=7 қараша 1917" what I need is the sub-string "7 қараша 1917". DocTAG does not allow me to highlight it, selecting the whole string. I guess it has something to do with the way DocTAG tokenises texts. Is there a work-around?

ISSUE 3: "mentions_ground_truths": [{
			"language": "english",
			"mentions": [{
				"stop": 163,
				"label": "Short_Answer",
				"start": 157,
				"mention_text": ""
Apart from the empty "mention_text", I was also wondering about "start" and "stop". In my text, the span in question starts at position 147 and ends at position 153. Why is there a shift in the positions?

**Comment by yeshpanovrustem** [comment]
ISSUE 3: "mentions_ground_truths": [{
			"language": "english",
			"mentions": [{
				"stop": 163,
				"label": "Short_Answer",
				"start": 157,
				"mention_text": ""
Apart from the empty "mention_text", I was also wondering about "start" and "stop". In my text, the span in question starts at position 147 and ends at position 153. Why is there a shift in the positions?

**Comment by OrnellaIrrera** [comment]
Dear Rustem,

Thank you for pointing these issues out, they could be helpful for the people who will use DocTAG in the future. 

For what concerns ISSUE 1: this issue is related to the cyrillic and arabic charset. While mention selection can be performed also with those characters, downloading and processing those strings works with latin characters at the moment. 
We plan to fix this issue in the next releases of the application.

For what concerns ISSUE 2 instead, tokenization is space (\s) based and it is not possible to select part of a word included between two single spaces. If you want to perform such a selection you should change the files provided during configuration. 

Empty mention text might be related to the ISSUE 1. For what concerns different start and stops: they are computed basing on the entire document content converted from json to string (hene considering not only the values of a json, but also the keys). The start and the stop are computed on the converted string and not on the single value of the json provided in input. This ensuresd that all the starts and the stops we found were unique for each document.


Feel free to contact me for any further information! 
Ornella

**Comment by yeshpanovrustem** [comment]
Ornella, thanks a lot for the quick response!
